name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - elixir: 1.11.0
            otp: 23.1.1
          - elixir: 1.12.2
            otp: 24.0.5
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1.8
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: mix deps.get
      - name: Check compile warnings
        run: mix compile --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      - name: Retrieve PLT Cache
        uses: actions/cache@v2
        id: plt-cache
        with:
          path: priv/plts
          key:
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{
            hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt
      - name: Run dialyzer
        run: mix dialyzer --no-check --halt-exit-status
      - name: Unit tests
        run: mix test
